# hyprlock — Gruvbox Material, minimal
$font = Iosevka Nerd Font Propo

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
    noise = 0.0117
    contrast = 0.9
    brightness = 0.75
    vibrancy = 0.17
    vibrancy_darkness = 0.0
}

general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(d4be98ff)
    font_size = 88
    font_family = $font
    position = 0, 110
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d %B')"
    color = rgba(928374ff)
    font_size = 17
    font_family = $font
    position = 0, 34
    halign = center
    valign = center
}

# Password input
input-field {
    monitor =
    size = 280, 48
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(45403dff)
    inner_color = rgba(1d2021ee)
    font_color = rgba(d4be98ff)
    check_color = rgba(ea6962ff)
    fail_color = rgba(ea6962ff)
    fade_on_empty = false
    placeholder_text = <span foreground="##928374">Enter password</span>
    rounding = 12
    position = 0, -40
    halign = center
    valign = center
}

# User hint
label {
    monitor =
    text =   $USER
    color = rgba(a89984ff)
    font_size = 14
    font_family = $font
    position = 0, -112
    halign = center
    valign = center
}
